config/routes.rb
Rails.application.routes.draw do




  devise_for :admins
  devise_for :talkers

  scope module: :public do
    root to: 'homes#top'
    resources :leagues, only: [:index, :show]
    resources :teams, only: [:index, :show]
      get 'search/sort_recommend', to: 'players#search', as: 'sort_recommend'
      get 'search/sort_comment', to: 'players#search', as: 'sort_comment'
    resources :players, only: [:index, :show, :edit, :update] do
      resources :recommends, only: [:create, :destroy]
      resources :comments, only: [:index, :edit, :update, :create, :destroy] do
        resource :favorites, only: [:create, :destroy]
      end
      collection do
        get 'search'
      end
    end
    resources :talkers, only: [:show, :edit, :update]
    resources :comments, only: [:index, :show, :edit, :update, :create, :destroy]
    resources :contacts, only: [:new, :create]
    get '/contacts/complete' => 'contacts#complete'
    resources :recommends
    resources :notifications, only: [:index]

  end

  namespace :admin do
    get 'homes/top'
    resources :leagues
    resources :teams
    resources :players
    resources :talkers
    resources :contacts, only: [:index, :show, :update]
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :recommends, dependent: :destroy
  has_many :recommended_talkers, through: :recommends, source: :talker
  has_many :notifications, dependent: :destroy

  belongs_to :talker, optional: true
  belongs_to :team

  enum foot: {right: 1, left: 2}
  enum position: {GK: 1, DF: 2, MF: 3, FW: 4}
  enum is_active: {active: 1, retirement: 2}

  def self.search(search)
    if search != ""
      Player.where('name LIKE(?) OR lead_name LIKE (?)', "%#{search}%", "%#{search}%" )
    else
      Player.all
    end
  end

  scope :recommend, -> {include(:recommend).sort}
  scope :comment, -> {include(:comment).sort}
  scope :old, -> {order(updated_at: :asc)}

  def create_notification_favorite!(current_talker, comment)#いいね通知
  favorite = Notification.where(["visitor_id = ? and visited_id = ? and player_id = ? and action = ?", current_talker.id, comment.talker_id, id, 'favorite'])

    if favorite.blank?
      notification = current_talker.active_notifications.new(
        player_id: id,
        comment_id: comment.id,
        visited_id: comment.talker_id,
        action: 'favorite'
      )

      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_talker, comment_id)#コメント通知
    temp_ids = Comment.select(:talker_id).where(player_id: id).where.not(talker_id: current_talker.id).distinct

    temp_ids.each do |temp_id|
      save_notification_comment!(current_talker, comment_id, temp_id['talker_id'])
    end
    save_notification_comment!(current_talker, comment_id, talker_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_talker, comment, talker_id)
      notification = current_talker.active_notifications.new(
        player_id: id,
        comment_id: comment.id,
        visited_id: comment.talker_id,
        action: 'comment'
      )

      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?

  end


end

app/controllers/admin/players_controller.rb
class Admin::PlayersController < ApplicationController
  before_action :authenticate_admin!
  def new
    @player = Player.new
    @teams = Team.all
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      redirect_to admin_players_path
    else
      render :index
    end
  end

  def index

    @players = Player.order(:birthday)
  end

  def show
    @player = Player.find(params[:id])

    today = Date.today.strftime("%Y%m%d").to_i
    birthday = Player.find(@player.id).birthday
    @age = (today - birthday) / 10000
    @year = birthday / 10000
    @month = birthday % 10000 / 100
    @day = birthday % 100
  end

  def edit
    @player = Player.find(params[:id])
    @teams = Team.all
  end

  def update
    @player = Player.find(params[:id])
    @player.update(player_params)
    redirect_to admin_players_path
  end

  private

  def player_params
    params.require(:player).permit(:team_id, :number, :position, :name, :lead_name, :country, :foot, :height, :weight, :is_active, :birthday)
  end
end

app/helpers/admin/players_helper.rb
module Admin::PlayersHelper
end

app/views/admin/players/_player.html.erb
  <h2><%= player.lead_name %></h2>
  <div class="recommends">
    <% if talker_signed_in? %>
      <% if current_talker.recommends.find_by(player_id: player.id) %>
        <%= link_to ' お気に入りから外す', player_recommend_path(player.id), method: :delete, class: "fas fa-backspace btn btn-warning" %>
      <% elsif current_talker.recommends.count < 11 %>
        <%= link_to ' お気に入りに登録する', player_recommends_path(player.id), method: :post, class: "fas fa-bookmark btn btn-warning" %>
      <% end %>
    <% end %>
  </div>
  
  <div class="row">
  <table class="table table-bordered col-md-6 player-data">
    <tr>
      <th>選手名</th>
      <td><%= player.name %></td>
    </tr>
    
    <tr>
      <th>所属チーム</th>
      <td><%= player.team.name %></td>
    </tr>
    
    <tr>
      <th>背番号</th>
      <td><%= player.number %></td>
    </tr>
    
    <tr>
      <th>ポジション</th>
      <td><%= player.position %></td>
    </tr>
    
    <tr>
      <th>国籍</th>
      <td><%= player.country %></td>
    </tr>
    
    <tr>
      <th>利き足</th>
      <td><%= player.foot_i18n %></td>
    </tr>
    
    <tr>
      <th>誕生日</th>
      <td>
        <%= @year %>年
        <%= @month %>月
        <%= @day %>日
      </td>
    </tr>
    
    <tr>
      <th>年齢</th>
      <td><%= @age %>歳</td>
    </tr>
    
    <tr>
      <th>身長</th>
      <td><%= player.height %>cm</td>
    </tr>
    
    <tr>
      <th>体重</th>
      <td><%= player.weight %>kg</td>
    </tr>
    
    <tr>
      <th></th>
      <td><%= player.is_active_i18n %></td>
    </tr>
  </table>
  
  <div class="comment-area">
    <% if current_page?(controller: "public/players", action: "show") && talker_signed_in? %>
    <div class="new-comment-box">
      <%= form_with(model:[player, comment], local:true) do |f| %>
        <%= f.text_area :body, placeholder: "コメントを入力してください", class: "comment-box" %>
        <%= f.submit "コメントする" %>
      <% end %>
    </div>
      
      <% player.comments.each do |comment| %>
      
      <% if comment.parent_id.present? || comment.id.blank? %>
        <% next %>
      <% end %>
      <div class="comment-container">
        
        <div class="comment-box">
          
          <%= link_to comment.talker.name, talker_path(comment.talker_id) %></br>
          <%= comment.body %>
          <%= comment.created_at.strftime('%Y/%m/%d %H:%M') %>
          
          <% if comment.favorited_by?(current_talker) %>
            <p>
            <%= link_to player_comment_favorites_path(player, comment), method: :delete do %>
              ♥<%= comment.favorites.count %>
            <% end %>
            </p>
          <% else %>
            <p>
            <%= link_to player_comment_favorites_path(player, comment), method: :post do %>
              ♡<%= comment.favorites.count %>
            <% end %>
            </p>
          <% end %> 
          
            <%= link_to '詳細を見る', comment_path(comment) %>
          <% if comment.talker == current_talker %>
            <%= link_to '編集する', edit_player_comment_path(comment.player, comment) %>
            <%= link_to '削除する', player_comment_path(comment.player, comment), method: :delete %>
          <% end %>
        </div>
          
        
          
        <div class="reply">
          <% comment.replies.order(:created_at).each do |reply| %>
            <%= link_to reply.talker.name, talker_path(reply.talker_id) %></br>
            <%= reply.body %>
            <%= reply.created_at.strftime('%Y/%m/%d %H:%M') %>
            <% if reply.favorited_by?(current_talker) %>
              <p>
              <%= link_to player_comment_favorites_path(player, reply), method: :delete do %>
                ♥<%= reply.favorites.count %>
              <% end %>
              </p>
            <% else %>
              <p>
              <%= link_to player_comment_favorites_path(player, reply), method: :post do %>
                ♡<%= reply.favorites.count %>
              <% end %>
              </p>
            <% end %> 
              <%= link_to '詳細を見る', comment_path(reply.id) %>
            <% if reply.talker == current_talker %>
              <%= link_to '編集する', edit_player_comment_path(reply.player, reply) %>
              <%= link_to '削除する', player_comment_path(reply.player, reply), method: :delete %>
            <% end %>
          <% end %>
        </div>
        
        <div class="reply-new">
          <%= form_with(model:[player,comment_reply]) do |f| %>
            <%= f.text_area :body, placeholder: "コメントを入力してください", class: "reply-box" %>
            <%= f.hidden_field :player_id, value: player.id %>
            <%= f.hidden_field :parent_id, value: comment.id %>
            <%= f.submit '返信する' %>
          <% end %>
        </div>
      </div>
      
      
      <% end %>
    <% end %>
  </div>
  </div>
  <%= link_to "#{@player.team.name}のページに戻る", team_path(@player.team_id) %>

app/views/admin/players/edit.html.erb
<h1>Admin::Players#edit</h1>
<div class="container">
  <%= form_with model: @player, url: admin_player_path(@player.id), local:true do |f| %>
  
  <table class="table">
    <tr class="form-group">
      <th><label for="name">選手名</label> </th>
      <td><%= f.text_field :name %></td>
    </tr>
    
    <tr class="form-group">
      <th><label for="lead_name">選手名(英語)</label> </th>
      <td><%= f.text_field :lead_name %></td>
    </tr>
    
    <tr class="form-group">
      <th><label for="team">所属チーム</label></th>
      <td><%= f.collection_select(:team_id, @teams, :id, :name) %></td>
    </tr>
    
    <tr class="form-group">
      <th><label for="number">背番号</label></th>
      <td><%= f.text_field :number %></td>
    </tr>
    
    <tr class="form-group">
      <th><label for="position">ポジション</label></th>
      <td><%= f.select :position, Player.positions.keys,  { class: 'form-control' , required: true } %></td>
    </tr>
    
    <tr class="form-group">
      <th><label for="country">国籍</label></th>
      <td><%= f.text_field :country %></td>
    </tr>
    
    <tr class="form-group">
      <th><label for="foot">利き足</label></th>
      <td><%= f.select :foot, Player.foots.keys, { class: 'form-control' , required: true } %></td>
    </tr>
    
    <tr class="form-group">
      <th><label for="birthday">誕生日</label></th>
      <td><%= f.text_field :birthday %>  例：19950915</td>
    </tr>
    
    <tr class="form-group">
      <th><label for="height">身長</label></th>
      <td><%= f.text_field :height %>cm</td>
    </tr>
    
    <tr class="form-group">
      <th><label for="weight">体重</label></th>
      <td><%= f.text_field :weight %>kg</td>
    </tr>
        
    <tr class="form-group">
      <th><label for="active">現役</label></th>
      <td><%= f.select :is_active, Player.is_actives.keys, { class: 'form-control' , required: true } %></td>
    </tr>
  </table>

  <div class="actions">
    <%= f.submit '変更する', class: "btn btn-success" %>
  </div>
  <% end %>
</div>

app/views/admin/players/index.html.erb
<h1>Admin::Players#index</h1>
<div class="container">

<%= link_to '追加する', new_admin_player_path, class: "btn btn-primary" %>
<table class="table">
  <thead>
    <tr>
      <th>選手名</th>
      <th>チーム名</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  
  <tbody>
    <% @players.each do |player| %>
    <tr>
      <td><%= player.name %></td>
      <td><%= player.team.short_name %></td>
      <td><%= link_to 'show', admin_player_path(player.id), class: "btn btn-primary" %></td>
      <td><%= link_to 'edit', edit_admin_player_path(player.id), class: "btn btn-primary" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'ホーム', admin_homes_top_path %>
</div>

app/views/admin/players/new.html.erb
<h1>Admin::Players#new</h1>
<div class="container">
  <%= form_with model: @player, url: admin_players_path, local:true do |f| %>
  
  <table class="table">
    <tr class="form-group">
      <th><label for="name">選手名</label> </th>
      <td><%= f.text_field :name %></td>
    </tr>
    
    <tr class="form-group">
      <th><label for="lead_name">選手名(英語)</label> </th>
      <td><%= f.text_field :lead_name %></td>
    </tr>
    
    <tr class="form-group">
      <th><label for="team">所属チーム</label></th>
      <td><%= f.collection_select(:team_id, @teams, :id, :name) %></td>
    </tr>
    
    <tr class="form-group">
      <th><label for="number">背番号</label></th>
      <td><%= f.text_field :number %></td>
    </tr>
    
    <tr class="form-group">
      <th><label for="position">ポジション</label></th>
      <td><%= f.select :position, Player.positions.keys, { class: 'form-control', required: true } %></td>
    </tr>
    
    <tr class="form-group">
      <th><label for="country">国籍</label></th>
      <td><%= f.text_field :country %></td>
    </tr>
    
    <tr class="form-group">
      <th><label for="foot">利き足</label></th>
      <td><%= f.select :foot, Player.foots.keys, { class: 'form-control' , required: true } %></td>
    </tr>
    
    <tr class="form-group">
      <th><label for="birthday">誕生日</label></th>
      <td><%= f.text_field :birthday %>  例：19950915</td>
    </tr>
    
    <tr class="form-group">
      <th><label for="height">身長</label></th>
      <td><%= f.text_field :height %>cm</td>
    </tr>
    
    <tr class="form-group">
      <th><label for="weight">体重</label></th>
      <td><%= f.text_field :weight %>kg</td>
    </tr>
    
    <tr class="form-group">
      <th><label for="active">現役</label></th>
      <td><%= f.select :is_active, Player.is_actives.keys, { class: 'form-control' , required: true } %></td>
    </tr>
  </table>

  <div class="actions">
    <%= f.submit '追加する', class: "btn btn-success" %>
  </div>
  <% end %>
</div>

app/views/admin/players/show.html.erb
<h1>Admin::Players#show</h1>
  <%= render 'admin/players/player', player: @player, comment: @comment %>

<%= link_to '編集する', edit_admin_player_path(@player.id) %>

<%= link_to 'ホーム', admin_homes_top_path %>
<%= link_to 'チームに戻る', admin_team_path(@player.team_id) %>