config/routes.rb
Rails.application.routes.draw do




  devise_for :admins
  devise_for :talkers

  scope module: :public do
    root to: 'homes#top'
    resources :leagues, only: [:index, :show]
    resources :teams, only: [:index, :show]
      get 'search/sort_recommend', to: 'players#search', as: 'sort_recommend'
      get 'search/sort_comment', to: 'players#search', as: 'sort_comment'
    resources :players, only: [:index, :show, :edit, :update] do
      resources :recommends, only: [:create, :destroy]
      resources :comments, only: [:index, :edit, :update, :create, :destroy] do
        resource :favorites, only: [:create, :destroy]
      end
      collection do
        get 'search'
      end
    end
    resources :talkers, only: [:show, :edit, :update]
    resources :comments, only: [:index, :show, :edit, :update, :create, :destroy]
    resources :contacts, only: [:new, :create]
    get '/contacts/complete' => 'contacts#complete'
    resources :recommends
    resources :notifications, only: [:index]

  end

  namespace :admin do
    get 'homes/top'
    resources :leagues
    resources :teams
    resources :players
    resources :talkers
    resources :contacts, only: [:index, :show, :update]
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/league.rb
class League < ApplicationRecord
  has_many :teams
end

app/controllers/admin/leagues_controller.rb
class Admin::LeaguesController < ApplicationController
  before_action :authenticate_admin!
  
  def new
    @league = League.new
  end

  def create
    @league = League.new(league_params)
    if @league.save
      redirect_to admin_leagues_path
    else
      render :index
    end
  end

  def index
    @leagues = League.all
  end

  def show
    @league = League.find(params[:id])
    @team = Team.where(league: @league.id)
    @teams = @team.order("short_name")
  end

  def edit
    @league = League.find(params[:id])
  end

  def update
    @league = League.find(params[:id])
    @league.update(league_params)
    redirect_to admin_leagues_path
  end

  private

  def league_params
    params.require(:league).permit(:name, :country, :division)
  end
end

app/helpers/admin/leagues_helper.rb
module Admin::LeaguesHelper
end

app/views/admin/leagues/edit.html.erb
<h1>Admin::Leagues#edit</h1>
<div class="container">
<table>
<%= form_with model: @league, url: admin_league_path(@league.id), local:true do |f| %>
  <tr class="form-group">
    <th><label for="country">国・地域</label></th>
    <td><%= f.text_field :country %></td>
  </tr>
 
  <tr class="form-group">
    <th><label for="division">部</label></th>
    <td><%= f.text_field :division %>部</td>
  </tr>
 
  <tr class="form-group">
    <th><label for="name">リーグ名</label></th>
    <td><%= f.text_field :name %></td>
  </tr>
</table>
 
  <div class="actions">
    <%= f.submit '変更する', class: "btn btn-success" %>
  </div>
<% end %>
</div>

app/views/admin/leagues/index.html.erb
<h1>Admin::Leagues#index</h1>
<div class="container">

<%= link_to '追加する', new_admin_league_path, class: "btn btn-primary" %>
<table class="table">
  <thead>
    <tr>
      <th>国・地域</th>
      <th>リーグ名</th>
      <th></th>
    </tr>
  </thead>
  
  <tbody>
    <% @leagues.each do |league| %>
    <tr>
      <td><%= league.country %></td>
      <td><%= link_to league.name, admin_league_path(league.id) %></td>
      <td><%= link_to 'edit', edit_admin_league_path(league.id), class: "btn btn-primary" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'ホーム', admin_homes_top_path %>
</div>

app/views/admin/leagues/new.html.erb
<h1>Admin::Leagues#new</h1>
<div class="container">
<table>
<%= form_with model: @league, url: admin_leagues_path, local:true do |f| %>
  <tr class="form-group">
    <th><label for="country">国・地域</label></th>
    <td><%= f.text_field :country %></td>
  </tr>
 
  <tr class="form-group">
    <th><label for="division">部</label></th>
    <td><%= f.text_field :division %>部</td>
  </tr>
 
  <tr class="form-group">
    <th><label for="name">リーグ名</label></th>
    <td><%= f.text_field :name %></td>
  </tr>
</table>
 
  <div class="actions">
    <%= f.submit '追加する', class: "btn btn-success" %>
  </div>
<% end %>
</div>
  

app/views/admin/leagues/show.html.erb
<h1>Admin::Leagues#show</h1>
<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th></th>
        <th>チーム名</th>
      </tr>
    </thead>
    
    <tbody>
    <% @teams.each do |team| %>
      <tr>
        <td><%= team.short_name %></th>
        <td><%= link_to team.name, admin_team_path(team.id) %></td>
      </tr>
    <% end  %>
    </tbody>
  </table>
  <%= link_to 'ホーム', admin_homes_top_path %>
  <%= link_to 'リーグ一覧に戻る', admin_leagues_path %>
</div>