config/routes.rb
Rails.application.routes.draw do




  devise_for :admins
  devise_for :talkers

  scope module: :public do
    root to: 'homes#top'
    resources :leagues, only: [:index, :show]
    resources :teams, only: [:index, :show]
      get 'search/sort_recommend', to: 'players#search', as: 'sort_recommend'
      get 'search/sort_comment', to: 'players#search', as: 'sort_comment'
    resources :players, only: [:index, :show, :edit, :update] do
      resources :recommends, only: [:create, :destroy]
      resources :comments, only: [:index, :edit, :update, :create, :destroy] do
        resource :favorites, only: [:create, :destroy]
      end
      collection do
        get 'search'
      end
    end
    resources :talkers, only: [:show, :edit, :update]
    resources :comments, only: [:index, :show, :edit, :update, :create, :destroy]
    resources :contacts, only: [:new, :create]
    get '/contacts/complete' => 'contacts#complete'
    resources :recommends
    resources :notifications, only: [:index]

  end

  namespace :admin do
    get 'homes/top'
    resources :leagues
    resources :teams
    resources :players
    resources :talkers
    resources :contacts, only: [:index, :show, :update]
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :league
  has_many :players, dependent: :destroy
  has_many :talkers, dependent: :destroy
  has_many :recommends, dependent: :destroy
end

app/controllers/admin/teams_controller.rb
class Admin::TeamsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @team = Team.new
    @leagues = League.all
  end

  def create
    @team = Team.new(team_params)
    if @team.save
      redirect_to admin_teams_path
    else
      render :index
    end
  end

  def index
    @teams = Team.order("short_name")
  end

  def show
    @team = Team.find(params[:id])
    @player = Player.where(team: @team.id)
    @players = @player.order("number")
  end

  def edit
    @team = Team.find(params[:id])
    @leagues = League.all
  end

  def update
    @team = Team.find(params[:id])
    @team.update(team_params)
    redirect_to admin_team_path(@team.id)
  end


    private

  def team_params
    params.require(:team).permit(:name, :short_name, :league_id, :stadium, :coach)
  end
end

app/helpers/admin/teams_helper.rb
module Admin::TeamsHelper
end

app/views/admin/teams/edit.html.erb
<h1>Admin::Teams#edit</h1>
<div class="container">
  <%= form_with model: @team, url: admin_team_path(@team.id), local:true do |f| %>
    <table>
      <tr class="form-group">
        <th><label for="league">所属リーグ</label></th>
        <td><%= f.collection_select(:league_id, @leagues, :id, :name) %></td>
      </tr>
      
      <tr class="form-group">
        <th><label for="team-name">チーム名</label></th>
        <td><%= f.text_field :name %></td>
      </tr>
      
      <tr class="form-group">
        <th><label for="team-name">略称名</label></th>
        <td><%= f.text_field :short_name %></td>
      </tr>
      
      <tr class="form-group">
        <th><label for="stadium">本拠地</label></th>
        <td><%= f.text_field :stadium %></td>
      </tr>
      
      <tr class="form-group">
        <th><label for="coach-name">監督名</label></th>
        <td><%= f.text_field :coach %></td>
      </tr>
    </table>
  
  <div class="actions">
    <%= f.submit '追加する', class: "btn btn-success" %>
  </div>
  <% end %>
</div>

app/views/admin/teams/index.html.erb
<h1>Admin::Teams#index</h1>
<div class="container">

<%= link_to '追加する', new_admin_team_path, class: "btn btn-primary" %>
<table class="table">
  <thead>
    <tr>
      <th>所属リーグ</th>
      <th>チーム名</th>
      <th></th>
    </tr>
  </thead>
  
  <tbody>
    <% @teams.each do |team| %>
    <tr>
      <td><%= team.league.name %></td>
      <td><%= link_to team.name, admin_team_path(team.id) %></td>
      <td><%= link_to 'edit', edit_admin_team_path(team.id), class: "btn btn-primary" %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'ホーム', admin_homes_top_path %>
</div>

app/views/admin/teams/new.html.erb
<h1>Admin::Teams#new</h1>
<div class="container">
  <%= form_with model: @team, url: admin_teams_path, local:true do |f| %>
    <table>
      <tr class="form-group">
        <th><label for="league">所属リーグ</label></th>
        <td><%= f.collection_select(:league_id, @leagues, :id, :name) %></td>
      </tr>
      
      <tr class="form-group">
        <th><label for="team-name">チーム名</label></th>
        <td><%= f.text_field :name %></td>
      </tr>
      
      <tr class="form-group">
        <th><label for="team-name">略称名</label></th>
        <td><%= f.text_field :short_name %></td>
      </tr>
      
      <tr class="form-group">
        <th><label for="stadium">本拠地</label></th>
        <td><%= f.text_field :stadium %></td>
      </tr>
      
      <tr class="form-group">
        <th><label for="coach-name">監督名</label></th>
        <td><%= f.text_field :coach %></td>
      </tr>
    </table>


    <div class="actions">
      <%= f.submit '追加する', class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/admin/teams/show.html.erb
<h1>Admin::Teams#show</h1>
<div class="container">
  <h2><%= @team.name %></h2>
  <div class="row flex-box">
  <div class="col-md-4">
    <h4>チーム情報</h4>
    <table class="table">
      <tr>
        <th>監督</th>
        <td><%= @team.coach %></td>
      </tr>
      
      <tr>
        <th>略称名</th>
        <td><%= @team.short_name %></td>
      </tr>
      
      <tr>
        <th>本拠地</th>
        <td><%= @team.stadium %></td>
      </tr>
    </table>
  </div>
  
  <div class="col-md-6">
    <h4>選手一覧</h4>
    <table class="table">
      <% @players.each do |player| %>
      <tr>
        <th><%= player.number %></th>
        <td><%= link_to player.name, admin_player_path(player.id) %></td>
        <td><%= player.position %></td>
      </tr>
      <% end %>
    </table>
  </div>
  </div>
  <%= link_to 'リーグに戻る', admin_league_path(@team.league_id) %>
</div>