config/routes.rb
Rails.application.routes.draw do




  devise_for :admins
  devise_for :talkers

  scope module: :public do
    root to: 'homes#top'
    resources :leagues, only: [:index, :show]
    resources :teams, only: [:index, :show]
      get 'search/sort_recommend', to: 'players#search', as: 'sort_recommend'
      get 'search/sort_comment', to: 'players#search', as: 'sort_comment'
    resources :players, only: [:index, :show, :edit, :update] do
      resources :recommends, only: [:create, :destroy]
      resources :comments, only: [:index, :edit, :update, :create, :destroy] do
        resource :favorites, only: [:create, :destroy]
      end
      collection do
        get 'search'
      end
    end
    resources :talkers, only: [:show, :edit, :update]
    resources :comments, only: [:index, :show, :edit, :update, :create, :destroy]
    resources :contacts, only: [:new, :create]
    get '/contacts/complete' => 'contacts#complete'
    resources :recommends
    resources :notifications, only: [:index]

  end

  namespace :admin do
    get 'homes/top'
    resources :leagues
    resources :teams
    resources :players
    resources :talkers
    resources :contacts, only: [:index, :show, :update]
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  has_many :replies, class_name: "Comment", foreign_key: :parent_id, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_notifications, class_name: "Notification", foreign_key: "player_id", dependent: :destroy
  has_many :reply_notifications,  class_name: "Notification", foreign_key: "comment_id", dependent: :destroy

  belongs_to :parent, class_name: "Comment", optional: true
  belongs_to :talker
  belongs_to :player

  validates :body, presence: true

  def favorited_by?(talker)
    favorites.where(talker_id: talker.id).exists?
  end

  def create_notification_by(current_talker)
    notification = current_talker.active_notifications.new(
      player_id: id,
      visited_id: talker_id,
      action: "favorite"
    )
    notification.save if notification.valid?
  end


end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :talker
  
  validates :is_check, inclusion: {in: [true, false]}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  
  belongs_to :talker
  belongs_to :comment
end

app/models/league.rb
class League < ApplicationRecord
  has_many :teams
end

app/models/notification.rb
class Notification < ApplicationRecord

  belongs_to :player, class_name: 'Comment',foreign_key: 'player_id', optional: true
  belongs_to :comment, class_name: 'Comment',foreign_key: 'comment_id', optional: true

  belongs_to :visitor, class_name: 'Talker', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'Talker', foreign_key: 'visited_id', optional: true
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :recommends, dependent: :destroy
  has_many :recommended_talkers, through: :recommends, source: :talker
  has_many :notifications, dependent: :destroy

  belongs_to :talker, optional: true
  belongs_to :team

  enum foot: {right: 1, left: 2}
  enum position: {GK: 1, DF: 2, MF: 3, FW: 4}
  enum is_active: {active: 1, retirement: 2}

  def self.search(search)
    if search != ""
      Player.where('name LIKE(?) OR lead_name LIKE (?)', "%#{search}%", "%#{search}%" )
    else
      Player.all
    end
  end

  scope :recommend, -> {include(:recommend).sort}
  scope :comment, -> {include(:comment).sort}
  scope :old, -> {order(updated_at: :asc)}

  def create_notification_favorite!(current_talker, comment)#いいね通知
  favorite = Notification.where(["visitor_id = ? and visited_id = ? and player_id = ? and action = ?", current_talker.id, comment.talker_id, id, 'favorite'])

    if favorite.blank?
      notification = current_talker.active_notifications.new(
        player_id: id,
        comment_id: comment.id,
        visited_id: comment.talker_id,
        action: 'favorite'
      )

      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_talker, comment_id)#コメント通知
    temp_ids = Comment.select(:talker_id).where(player_id: id).where.not(talker_id: current_talker.id).distinct

    temp_ids.each do |temp_id|
      save_notification_comment!(current_talker, comment_id, temp_id['talker_id'])
    end
    save_notification_comment!(current_talker, comment_id, talker_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_talker, comment, talker_id)
      notification = current_talker.active_notifications.new(
        player_id: id,
        comment_id: comment.id,
        visited_id: comment.talker_id,
        action: 'comment'
      )

      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?

  end


end

app/models/recommend.rb
class Recommend < ApplicationRecord
  belongs_to :talker
  belongs_to :player
end

app/models/talker.rb
class Talker < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :comments, dependent: :destroy
  has_many :contacts
  has_many :favorites, dependent: :destroy
  has_many :recommends, dependent: :destroy
  has_many :players, dependent: :destroy
  has_many :recommendes_players, through: :recommend, source: :player
  
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :league
  has_many :players, dependent: :destroy
  has_many :talkers, dependent: :destroy
  has_many :recommends, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?


  def after_sign_in_path_for(resource)
    byebug
    if resource_name == :talker
      talker_path(resource)
    elsif resource_name == :admin
      admin_homes_top_path(resource)
    end
  end

  def after_sign_out_path_for(resource)
    root_path
  end




  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/leagues_helper.rb
module Admin::LeaguesHelper
end

app/helpers/admin/players_helper.rb
module Admin::PlayersHelper
end

app/helpers/admin/talkers_helper.rb
module Admin::TalkersHelper
end

app/helpers/admin/teams_helper.rb
module Admin::TeamsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FootballTalkers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/22d6edb043.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: green;">
        <div class="container container-header">
          <a class="navbar-brand" href="/">Football Talkers</a>
          
          <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          
          <div class="collapse navbar-collapse" id="navbarNavDropdown" style>
            <ul class="navbar-nav ml-auto">
              <% if talker_signed_in? %>
                <%= link_to "マイページ", talker_path(current_talker.id), class: "fas fa-home nav-link text-light" %>
                <%= link_to "ログアウト", destroy_talker_session_path, method: :delete, class: "fas fa-sign-out-alt nav-link text-light" %>
                <%= link_to 'リーグ一覧', leagues_path, class: "fas fa-flag nav-link text-light" %>
                <%= link_to 'チーム一覧', teams_path, class: "fas fa-users nav-link text-light" %>
                <%= link_to '選手一覧', players_path, class: "fas fa-tshirt nav-link text-light" %>
                <%= link_to 'お問い合わせ', new_contact_path, class: "fas fa-question-circle nav-link text-light" %>
              <% else %>
                <%= link_to "新規登録", new_talker_registration_path, class: "fas fa-user-plus nav-link text-light" %>
                <%= link_to "ログイン", new_talker_session_path, class: "fas fa-sign-in-alt nav-link text-light" %>
                <%= link_to 'リーグ一覧', leagues_path, class: "fas fa-flag nav-link text-light" %>
                <%= link_to 'チーム一覧', teams_path, class: "fas fa-users nav-link text-light" %>
                <%= link_to '選手一覧', players_path, class: "fas fa-tshirt nav-link text-light" %>
              <% end %>
            
        
            </ul>
          </div>
        </div>
      </nav>
    </header>
    

    <%= yield %>
  </body>
</html>